### ISSUE TITLE
Les enfants manquent

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/lacriee-site#1]
https://rennes-lacriee.netlify.app/fr/saisons/saison-2022-2023/expositions-2022-2023/

**Comment by alexisben** [comment]
On a un pb, il n'y pas les enfants dans la data : 

https://github.com/noesya/rennes-lacriee/blob/main/content/fr/pages/saisons/saison-2022-2023/expositions-2022-2023/_index.html

**Comment by arnaudlevy** [comment]
@pabois @SebouChu il faudrait investiguer dans qqs semaines, quand le temps sera plus calme
