### ISSUE TITLE
Date avec un 0 initial

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/lacriee-site#12]
Dans notre charte graphique, les dates qui débutent par un chiffre sont précédées d'un zéro "02 février 2024" et non "2 février 2024". Est-ce réglable ?

**Comment by alexisben** [comment]
Je ne sais pas comment gérer dans le thème car osuny renvoie des dates déjà formatées :

```
short: >-
      Du 1 septembre 2023 au 30 juin 2024
    long: >-
      Du vendredi 1 septembre 2023 au dimanche 30 juin 2024
    two_lines:
      short: >-
        1 septembre 2023<br>30 juin 2024
      long: >-
        Vendredi 1 septembre 2023<br>Dimanche 30 juin 2024
```

**Comment by alexisben** [comment]
@arnaudlevy t'as une idée ?

**Comment by arnaudlevy** [comment]
Oui : on ne fait pas.
