### ISSUE TITLE
Erreur de resize

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/lacriee-site#13]
<img width="306" alt="Capture d’écran 2024-01-29 à 17 13 05" src="https://github.com/noesya/lacriee-site/assets/2088968/01f940d3-6657-4166-8c0c-9507ef285a42">

**Comment by arnaudlevy** [comment]
L'image est déformée

**Comment by alexisben** [comment]
J'arrive pas à reproduire, tu as plus de contexte ?

**Comment by arnaudlevy** [comment]
tu vas sur la home, tu scroll, tu vois l'image déformée

**Comment by alexisben** [comment]
@Olivia206 c'est pour toi celui là
